config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  match '/', to: 'home#index', via: 'get', as: 'home'
  match 'stream', to: 'stream#index', via: 'get', as: 'stream'
  match 'about', to: 'home#about', via: 'get', as: 'about'
  match 'stream/:name', to: 'stream#show', via: 'get', as: 'custom_image'
  match 'map', to: 'map#index', via: 'get', as: 'map'
  match 'gyro', to: 'gyro#index', via: 'get', as: 'gyro'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  require 'Readfile'
end

app/controllers/gyro_controller.rb
class GyroController < ApplicationController
  def index
    gyrofile = Tail.new('./streamed_data/gyro.txt').tail(1).flatten
    @gyrotime = gyrofile.first
    @gyrodata = gyrofile.second.gsub('euler','')[3..-1].chomp.split('   ')
    unless @gyrodata.present? then @gyrodata = "N/A" end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latestimage = Image.new("./streamed_images/").latest.flatten
    #for gyro cube
      gyrofile = Tail.new('./streamed_data/gyro.txt').tail(1).flatten
      @gyrotime = gyrofile.first
      @gyrodata = gyrofile.second.gsub('euler','')[3..-1].chomp.split('   ')
      unless @gyrodata.present? then @gyrodata = "N/A" end
    #end gyro cube
  end

  def about
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/controllers/stream_controller.rb
class StreamController < ApplicationController
  def index
    gyrofile = Tail.new('./streamed_data/gyro.txt').tail(1).flatten
    @gyrotime = gyrofile.first
    @gyrodata = gyrofile.second
    unless @gyrodata.present? then @gyrodata = "N/A" end
    humidityfile = Tail.new('./streamed_data/humidity.txt').tail(1).flatten
    @humiditytime = humidityfile.first
    unless @humiditydata.present? then @humiditydata = "N/A N/A" end
    @humiditydata = humidityfile.second.split(' ')
    @humiditytemp = @humiditydata.first.gsub('Temp=', '').gsub('*',' ')
    @humidity = @humiditydata.second.gsub('Humidity=', '')
    externalfile = Tail.new('./streamed_data/external.txt').tail(1).flatten
    @externaltime = externalfile.first
    @externaldata = externalfile.second.gsub('(','').gsub(')','')
    unless @externaldata.present? then @externaldata = "N/A" end
  end

  def show
    send_file File.join('./streamed_images/',params[:name] + '.png'), :disposition => 'inline'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #for nice notifications with toastr
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      puts type

      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/gyro_helper.rb
module GyroHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/views/gyro/_gyro.js.erb
$( document ).ready(function() {
var scene, camera, renderer;
      var WIDTH  = $('#gyro').innerWidth() - 50;
      var HEIGHT = '350';
      var SPEED = 0.01;
      function init() {
          scene = new THREE.Scene();
          initCube();
          initCamera();
          initRenderer();
          document.getElementById("gyro").appendChild(renderer.domElement);
      }
      function initCamera() {
          camera = new THREE.PerspectiveCamera(70, WIDTH / HEIGHT, 1, 10);
          camera.position.set(0, 5, 7);
          camera.lookAt(scene.position);
      }
      function initRenderer() {
          renderer = new THREE.WebGLRenderer({ antialias: true });
          renderer.setSize(WIDTH, HEIGHT);
      }
      function initCube() {
          cube = new THREE.Mesh(new THREE.BoxGeometry(4, 4, 4), new THREE.MeshNormalMaterial());
          scene.add(cube);
      }
      function render() {
          requestAnimationFrame(render);
          renderer.render(scene, camera);
      }
      var angle = 0;
      init();
      render();
      //////////////////////////////////////////////////
      //var socket = io();
      //socket.on('data', function(data){
      <% unless @gyrodata == "N/A" %>
        rotateCube(Number(<%= @gyrodata.first %>), Number(<%= @gyrodata.second %>), Number(<%= @gyrodata.third %>));
      <% end %>
      //});
      function rotateCube(yaw, pitch, roll) {
          cube.rotation.x = roll * (Math.PI/180);
          cube.rotation.z = pitch * (Math.PI/180);
          cube.rotation.y = yaw * (Math.PI/180);
      }

});

app/views/gyro/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body homepanel" style="width: 100%;">
        <h3 class="paneltitle">Current Gyro Estimation</h3>
        <h4><%= @gyrodata.first %>, <%= @gyrodata.second %>, <%= @gyrodata.third %></h4>
        <div id="gyro" style="width: 100%; height: 350px;"></div>
      </div>
    </div>
  </div>
</div>
<script>
  <%= render partial: 'gyro.js.erb' %>
</script>

app/views/home/about.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-body homepanel">
        <h3 class="paneltitle">About NearSpacePi</h3>
        <p>NearSpacePi is a joint project by <a href="https://twitter.com/ccnppro">Mike Rickert</a> and <a href='mailto: quantumchaos87@gmail.com'>Asa Sallee</a> to fly a raspberry pi above 60,000ft while streaming live telemetry/video from the in-air device.</p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-body homepanel">
        <h3 class="paneltitle">Stats/readings</h3>
        <ul class="list-group">
          <li class="list-group-item">Last updated: </li>
          <li class="list-group-item">Internal Temp: </li>
          <li class="list-group-item">Humidity: </li>
          <li class="list-group-item">External Temp: </li>
          <li class="list-group-item">Barometer: </li>
          <li class="list-group-item">Gyro: </li>
          <li class="list-group-item">GPS: </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-body homepanel">
        <h3 class="paneltitle">Live feed</h3>
        <p>Most recent image: <%= time_ago_in_words(@latestimage.first) %> ago</p>
        <%= image_tag custom_image_path(@latestimage.second), style: 'max-width: 300px; max-height: 300px;' %>
      </div>
    </div>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
      <div class="panel-body homepanel">
        <h3 class="paneltitle">Known GPS coords</h3>
        <div id="map" style='width: 800px; height: 400px;'></div>
      </div>
    </div>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-body homepanel" style="width: 100%;">
        <h3 class="paneltitle">Current Gyro Estimation</h3>
        <h4><%= @gyrodata.first %>, <%= @gyrodata.second %>, <%= @gyrodata.third %></h4>
        <div id="gyro" style="width: 100%; height: 350px;"></div>
      </div>
    </div>
  </div>
</div>
<script>
  <%= render partial: 'gyro/gyro.js.erb' %>
</script>
<script>
  <%= render partial: 'map/map.js.erb' %>
</script>

app/views/layouts/_footer.html.erb
<small class="footer">NearSpacePi is a project by <a href="https://twitter.com/ccnppro">Mike Rickert</a> and <a href='mailto: quantumchaos87@gmail.com'>Asa Sallee</a></small>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
  		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
  			<span class="sr-only">Toggle navigation</span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  			<span class="icon-bar"></span>
  		</button>
    	<%= link_to root_url, class: "navbar-brand" do %>
        <i>NearSpace</i><b>Pi</b>
    	<% end %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Map', map_path %></li>
          <li><%= link_to 'Gyro', gyro_path %></li>
          <li><%= link_to 'Stream', stream_path %></li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_nprogress.html.erb
<script>
  $(document).on('page:fetch',   function() { NProgress.start(); });
  $(document).on('page:change',  function() { NProgress.done(); });
  $(document).on('page:restore', function() { NProgress.remove(); });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script> <!-- for google maps -->
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script> <!-- for google maps -->
  <script src="http://cdnjs.cloudflare.com/ajax/libs/three.js/r69/three.js"></script> <!-- for gyro -->
  <title>NearSpacePi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/nprogress' %>
    <% if notice or alert %>
      <%= custom_bootstrap_flash %>
    <% end %>
    <%= yield %>
  </div>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/map/_map.js.erb
$( document ).ready(function() {
  $('#map').width($('#map').innerWidth() - 50);
  $('#map').height('350px');
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": 51.5033630,
        "lng": -0.1276250,
        "infowindow": "test!"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
});

app/views/map/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-body homepanel" style="width: 100%;">
        <h3 class="paneltitle">Known GPS coords</h3>
        <div id="map" style="width: 100%; height: 100%;"></div>
      </div>
    </div>
  </div>
</div>
<script>
  <%= render partial: 'home/map.js.erb' %>
</script>

app/views/stream/index.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="panel panel-default">
      <div class="panel-body homepanel">
        <h3 class="paneltitle">Raw data readouts</h3>
        <p>gyro last updated <%= time_ago_in_words(@gyrotime) %> ago</p>
        <p>latest gyro reading: <b style="color: blue"><%= @gyrodata %></b></p>
        <p>humidity last updated <%= time_ago_in_words(@humiditytime) %> ago</p>
        <p>latest humidity reading: <b style="color: blue"><%= @humidity %></b></p>
        <p>internal temp last updated <%= time_ago_in_words(@humiditytime) %> ago</p>
        <p>latest internal temp reading: <b style="color: blue"><%= @humiditytemp %></b></p>
        <p>external temp last updated <%= time_ago_in_words(@externaltime) %> ago</p>
        <p>latest external temp reading: <b style="color: blue"><%= @externaldata %>C</b></p>
      </div>
    </div>
  </div>
</div>